name: Build & Release

on:
    push:
        tags: [ "*" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: maven
            -   name: Build with Maven
                run: mvn -B package
            -   name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    path: target/*.jar
            -   name: "Release"
                uses: "marvinpinto/action-automatic-releases@latest"
                with:
                    repo_token: "${{ secrets.GITHUB_TOKEN }}"
                    prerelease: false
                    files: target/*.jar